### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by negsadr** [UBC-MDS/nba_player_stat#50]
> **Congratulations on finishing milestone 1!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  
> We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
> If anything is unclear, please feel free to ask questions in this issue thread.

---

## 1. Submission instructions
rubric={mechanics:4}

Well done!

## 2. Developing your Shiny App
rubric={mechanics:15, quality:5, viz:15, accuracy:7}

- [ ] The apps's reactivity is working as expected (for example, if it is a dropdown menu, modifiying the option will change the related plot)  **-3 mechanics**

- [ ] Labels in the Input widgets are missing. These are necessary to allow the user a clear understanding the dashboard functionality. **-2 viz**

- [ ] Plot axis are missing or are the name of the dataset variables. Lack of units. **-3 viz**
  
Comments:
-The third radial bar is not reacting to filters.
-In the “Points/Games for the whole career” plot, there is no colour legend.
-Used variable names like G, TM.
-Years should not include “,” (for example 1,998).
-I strongly recommend adding the select feature for the player name.

## 3. Reflection
rubric={reasoning:6}

Well done!

## 4.Improve the README
rubric={reasoning:6}

Well done!

**Comment by CChCheChen** [comment]
@negsadr thank you very much for your time and effort to evaluating our work and we greatly appreciate your feedback.

While I have a few concern regarding the interaction components.

The radar plot do react to the change of the filters, maybe you still have the whole career check box checked,

The Point/Games without legends is because the legends will take a lot of space which make the plot look odd, that's why have have the information shown when user hover over the mouse to the certain bar in the plot.

Also the plots do have the proper axis title instead of the G, TM which can be proved by checking the code at line 397.

Can you please kindly recheck and let me know if we can get those deducted marks back.

All the best,
Chen
